INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'normalize']

DATASET:
  NAME: 'VLCS'

MODEL:
  BACKBONE:
    NAME: 'curesnet18'
    PRETRAINED: True
  HEAD:
    NAME: 'mlp'
    HIDDEN_LAYERS: 256
    ACTIVATION: 'relu'